# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20170128_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogReg.User'),
        ),
    ]
